version: '3'

services:

  contracts:
    build:
      context: "./contracts"
    restart: always
    ports:
      - 8545:8545

  # plugin:
  #   build:
  #     context: "./frontend"
  #   restart: always
  #   ports:
  #     - 3010:3000

  cog:
    image: playmint/cog-services:latest
    pull_policy: always
    restart: always
    entrypoint:
    - /bin/ash
    - -eu
    - -c
    - |
      echo "waiting"
      /wait-for -it contracts:8545 -t 300
      echo "starting"
      exec /ds-node
    environment:
      CHAIN_ID: "1337"
      SEQUENCER_PRIVATE_KEY: "095a37ef5b5d87db7fe50551725cb64804c8c554868d3d729c0dd17f0e664c87"
      SEQUENCER_PROVIDER_URL_HTTP: "http://contracts:8545"
      SEQUENCER_PROVIDER_URL_WS: "ws://contracts:8545"
      INDEXER_WATCH_PENDING: "false"
      INDEXER_PROVIDER_URL_HTTP: "http://contracts:8545"
      INDEXER_PROVIDER_URL_WS: "ws://contracts:8545"
    ports:
      - 8080:8080
    depends_on:
      - contracts

  shell:
    image: playmint/ds-shell:latest
    pull_policy: always
    restart: always
    ports:
      - 3000:3000

  # map:
  #   image: playmint/ds-map:latest

